version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: auth_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: headache
      POSTGRES_DB: authDB
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - soar-network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "50052:50052" 
      - "2006:2006"    
    environment:
      - SERVER_GRPC_PORT=50058
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=headache
      - POSTGRES_DB=authDB
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - soar-network

volumes:
  pgdata:

networks:
  soar-network:
    driver: bridge